import { TAddTVocabulary } from '../types/vocabularies.types';

const en: TAddTVocabulary = {
  headerLink: 'Main Page',
  userLogin: 'Login',
  newArticle: 'New post',
  settings: 'Settings',
  administration: 'Administration',
  userList: 'User list',
  administratorRole: 'Administrator',
  grantAdminRole: 'Grant admin role',
  userRole: 'User',
  exitProfile: 'Exit',
  mainTitle: 'When I grow up',
  mainSubtitle: 'What it’s like to be a junior in a turbulent world',
  popularTags: 'Popular tags',
  popularContent: 'Popular content',
  articleEnter: 'Read More',
  freshContent: 'New content',
  comments: 'Comments',
  editArticle: 'Edit article',
  deleteArticle: 'Delete article',
  sendComment: 'Send comment',
  articleName: 'Article title',
  articleAbout: 'About',
  articleImage: 'URL of images (optional)',
  articleText: 'Article Text',
  tags: 'Tags (comma-separated)',
  saveArticle: 'Create article',
  deletepopuptext: 'By clicking «Delete Entry», the material will be removed without the possibility of recovery. ',
  subscribe: 'Subscribe',
  unsubscribe: 'Unsubscribe',
  register: 'Sign Up',
  userName: 'User Name',
  userEmail: 'Email',
  password: 'Password',
  confirmPassword: 'Confirm password',
  urlImage: 'User avatar URL',
  newPassword: 'New password',
  refreshUser: 'Update settings',
  usersettings: 'Your setings',
  publishArticle: 'Publish your material',
  pageMessage: 'Page not found. To read blog, go to Home',
  publishComment: 'Post comment',
  loading: 'Please wait, loading...',
  footerMessage: 'Created by Yandex Practicum Students, Red.Types Lakers team',
  aboutUser: 'About you',
  noPageText: ' Page not found',
  goPageOnPage: 'To read the blog, go to ',
  npPageLink: 'Main',
  nickname: 'Display name',
  tagsInForm: 'Tags',
  messageAboutMissingTags: '&nbsp;&nbsp;You don\'t have subscriptions to tags',
  publish: 'Publish',
  decline: 'Decline',
  published: 'Published',
  removePublish: 'Remove from publication',
  invitionCode: 'Enter registration code',
  generateInviteCode: 'Generate code',
  youSubscribedToTheTag: 'You subscribed to the tag #',
  space: '',
  OK: 'OK',
  400: 'Validation error - Invalid value passed',
  421: 'The limits on the number of requests per unit of time have been exceeded - You are accessing the server too often, try again in a few minutes',
  403: 'Access is denied, you have no rights, there are only duties',
  404: 'page not found',
  409: 'Uniqueness validation error - This username /email is already in use',
  401: 'Authorization error or an incorrect login/password pair was passed',
};

export default en;
